language: java
sudo: false
jdk:
- oraclejdk8
script:
- if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then exit; fi
- mvn clean compile findbugs:check package
env:
  global:
  - secure: NHrfs1KGRPy2gizlWbe1Gkt5bVbFOBLCoSMHJV+X2gnfo9ZLvj4xruYZ6oAXFMhlUEp2nQDwI36IJac/CuXU0+Bqrp2KErMxVFTmRY3DiyX/6ed0PHjxTMac7aKnyhfoxV4q8pANhepPgCJqP5BGKl89/5GnJlqxiPmaPimwyBiEb6IZSNtT2h0mUcjiFhxttjibiN2NFw6cKPyD/Ax2Nb6k6zV1W/Qkrx+ktwpbxVCtl+Tp2q0INPs1L1gw7qXuk27CnCrq0mCk4N/J0nogLQW6ba2orx04Zyy9+8oWi/NmJfV4Y0v87YDEZQkEc1/wQquRr/OS+mYlEa9dNjS7DNFAFFk+HFL68+HzzfkO3lmYDy1/eeiwZs4U8NxwJQrK7lsS9+fwczM9fnsNj+H5FnonAmR59RfS9F4sqcJBf9xygr9BiBXPncWYEqqfxogrO7P4S7DnA7ty02G+D/cXeevbDDD0AFoEi9hmKLsiviGIoEag0VK6KoYajgGd0eqUCEmrJBNEttWlBo5wJqklcskh3rEuCRBHTw+KSQftAssSArUoAKbv4H6jd9YuaVqp84XQK1oBBxSlx3DhZC8g+gEJDzrUojXfPTI5I/c+wmoOi2pJzlQ1gec3yHj8iJntyk4eifLHGOrn5XHx18KAf8au+Jzib7qLm9IEk/yxDH4=
addons:
  apt:
    packages:
    - libc6:i386
  coverity_scan:
    project:
      name: martinpaljak/capfile
      description: capfile
    notification_email: martin@martinpaljak.net
    build_command: mvn clean compile
    branch_pattern: coverity
deploy:
  file:
  - target/capfile.jar
  - target/capfile.exe
  provider: releases
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: Giz0MG0oPm4N09nVrBinMAoztBIoiqA4uYT57NmOhrtluRRLHB8oWfWPZXkIVoEu+YdWJzqK2ZJRt6YDu6/g5yWO1JGkVEMYRmBwyLHRQZkt5pAFAcJBHYLtMOiUc+fnG+sDVsMwYbydizKe14dBO3+VkNWkIYVCa2tyf0kLLSt5tOiP2w+fJ694iMWy9er+UqEUb8kllIjRB1dLeT64wWsvQRZDiBrmnav8nn2cwBH06QbNRi0Lw390pVRCAa7nfvCpZMOYZsPiGurtVsLZC6eHTFmxmJvQ4da45p5lswQeRKDrxm0uerZKJmrwnabG9IlS50522108pY3655xBELu0/vh1cS3hsPSWSysml2ojDFsqF/Z9voMXpA0SARaQaXFsp7gQppMFWb/K7EOXJa11knXHYHLOwajXF3nEtc/KKdmadey35DhBhzqNSDCMxQdciRHJXOJ0jrfVGP9S/l5OTOqDzEnpiIgPAYMewlzSmFMSAj6gH/LguQlESnjO+LrUMs3zwdMIsIEV+JHoFfuicxdyTdcJKsTwuFX2M+UeWHykvmXfnC29ANy9tZcDGNo03HUqMxuvr3YTTtJ+plBCCS39MyRgeSHJBJQzsc/s/GQvyYCcRfh2FWOZ6K4djICEepb7yN20v8pMcIqRUNg5xlhzVeKNqm2OdXuFHWc=
  api-key:
    secure: mxH9+0gMs7ny7KJ2cZJfv6vR0v7bb5n0BayjRcO6TjIgI8SzW/9xYG4l8aj9CwYARJp/T0b3WyKl3wPE8e1nage9Wgi5FhbGzLycpuMOKmV/UckfbU2icubsbiOEnMxZySJtXcDen964P3Sp4vrfnAvt/jY9gk7ddW77rc6hBKYYGEK33H/9dV3tM9bMHwJLasm3fuPJCcEr+hMBwlMjv3Qvb7Q+Q+NziKSs9rYh1FAaa/+8JvNAOLgymp+JBsF0bzOBsjLXMQd2gIm2h3KqHb067rOUS4hek4b39QQMAbRqW5yoJRHu71jyi2eVRGEksIOjdHNc56TZoKQjwRxX8VX5H14/yqgbUHEQ139oV4Jjbmu1kWvwVJIqTrJGCj0q8QqyiIASpoKXRalgAroYCdpfYbfZI3lIn8xEYl9R9fe+rZcF5KUiG1YF1swSG1kQpPnZqL0ADnYb7eVU+UtFPqvvc2g1IsVpNiLbi8foyMvzXz1+grfr+ycjJ07R/wKM9aUBOqb3d8gACq9vWs1SCJiVK9HMsEKgShbtcjOc3VWfITWJKLxIdBIyvUVeF8VS6YjZ4Y+bGPXlAl2Mxf7MG7nqKvDaLvkl2KYCNoBdP5aZLVuJqmnTMCRm4jAIFdOcDqwabmpn2tvsYB99kNYleP27OVZCGee7v4d8KXpfw6s=
cache:
  directories:
  - "~/.m2"
